# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d943451ec2372387a8a92f09c4d5127faf66e9d62778eeb9ba3b1265af5a6e5bbc2bb090129aab2c50c06ee52bffc11d7cda301800246098f9d357299e8785

test:
  secret_key_base: 61883c872b72998760a307595f445d56abe382ab5ac40631e4dc8e2d9de7af0eb3ff81944dd86578a69dd2bba29acbdb4350826ca1a80ab2329f85fe21f28a19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
